version: '3.8'
services:
 web:
  build:
   context: .
   args:
    NODE_ENV: development
 
  volumes:
   - .:/usr/src/app
   - /usr/src/app/node_modules

  command: ./node_modules/.bin/nodemon -L server.js